Base_Application/urls.py
from django.urls import path
from Base_Application import views as base_views

app_name = "Base_Application"

urlpatterns = [
    path("", base_views.homepage, name="homepage"),
    path("about_us", base_views.about_us, name="about_us"),
    path("contact_us", base_views.contact_us, name="contact_us"),
]

TicketManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Base_Application.urls")),
    path("user/", include("User_Application.urls")),
    path("ticket_admin/", include("Ticket_Admin.urls")),
]

Ticket_Admin/urls.py
from django.urls import path
from Ticket_Admin import views as admin_views

app_name = "Ticket_Admin"

urlpatterns = [
    path("", admin_views.login, name="login"),
    path("logout", admin_views.logout, name="logout"),
    path("home", admin_views.homepage, name="homepage"),
    path("view_user_tickets", admin_views.view_all_tickets, name="viewTickets"),
    path("edit_ticket-status/<int:ticket_id>", admin_views.edit_ticket_status, name="editTicketStatus"),
    path("update_ticket-status", admin_views.update_ticket_status, name="updateTicketStatus"),
]

User_Application/urls.py
from django.urls import path
from User_Application import views as user_views

app_name = "User_Application"

urlpatterns = [
    path("", user_views.login, name="login"),
    path("registration", user_views.registration, name="registration"),
    path("logout", user_views.logout, name="logout"),
    path("home", user_views.homepage, name="homepage"),
    path("new_ticket", user_views.new_ticket, name="newTicket"),
    path("new_ticket_submission", user_views.new_ticket_save, name="newTicketSubmission"),
    path("view_my_tickets", user_views.view_tickets, name="viewTickets"),
    path("edit_my_ticket/<int:ticket_id>", user_views.edit_ticket, name="editUserTicket"),
    path("edit_my_ticket", user_views.update_user_ticket, name="UpdateUserTicket"),
]

User_Application/models.py
from django.db import models
import datetime


# Create your models here.

class UserRegistrationData(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email_id = models.EmailField()
    contact_number = models.BigIntegerField()
    password = models.CharField(max_length=50)

    objects = models.Manager()

    def __str__(self):
        return "%s" % self.first_name


class UserTicket(models.Model):
    user = models.ForeignKey(UserRegistrationData, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    create_on = models.DateTimeField(default=datetime.datetime.now, null=True)
    status = models.CharField(max_length=100, default="Under Review", null=True)

    objects = models.Manager()

    def __str__(self):
        return "%s" % self.title

User_Application/forms.py
from django import forms
from User_Application.models import UserRegistrationData, UserTicket


# writing forms here

class UserRegistrationDataForm(forms.ModelForm):
    class Meta:
        model = UserRegistrationData
        fields = "__all__"


class UserTicketForm(forms.ModelForm):
    class Meta:
        model = UserTicket
        fields = ["user", "title", "description"]

User_Application/views.py
from django.shortcuts import render
from User_Application.models import UserRegistrationData, UserTicket
from User_Application.forms import UserRegistrationDataForm, UserTicketForm


# Create your views here.

# Creating User Login View
def login(request):
    if request.method == "POST":
        # requesting data from the user
        email = request.POST["email_id"]
        password = request.POST["password"]
        user_count = UserRegistrationData.objects.filter(email_id=email, password=password)

        # Initiating Exception Handling
        try:
            # Checking whether a user is registered with the given Email
            if UserRegistrationData.objects.filter(email_id=email).exists():
                context = {"user_doesnt_exist": "An account with " + email + " doesn't Exist. Please Register!"}
                return render(request, "user_registration.html", context)
            # Checking whether the given email and password match
            elif len(user_count) == 0:
                context = {"invalid_credentials": "You have entered Invalid Credentials :("}
                return render(request, "user_login.html", context)
            else:
                # Creating a session and logging in, since the user exists with given details
                request.session["email"] = email
                user_data = UserRegistrationData.objects.get(email_id=email)
                context = {"login_success": "Welcome " + user_data.first_name}
                return render(request, "user_homepage.html", context)

        # Logging any exceptions that might have triggered
        except Exception as error:
            print("Login Error: ", error)
            context = {"error_message": "Uh oh! An unexpected error occurred!"}
            return render(request, "user_login.html", context)

    return render(request, "user_login.html", {})


# Creating User Registration View
def registration(request):
    if request.method == "POST":
        email = request.POST["email_id"]

        try:
            user_form_data = UserRegistrationDataForm(request.POST)
            print("User Form Data Errors: ", user_form_data.errors)

            # Filtering Duplicate Email Registration
            if UserRegistrationData.objects.filter(email_id=email).exists():
                context = {"user_exists": "User with " + email +
                                          "already exists! Please register with another email :)"}
                return render(request, "user_registration.html", context)
            # Saving User Data in Database if there's no Duplicate
            elif user_form_data.is_valid():
                user_form_data.save()
                context = {"success": "Registration Successful! Login for full experience"}
                return render(request, "user_login.html", context)

        except Exception as error:
            print("Registration Error: ", error)
            context = {}
            return render(request, "user_registration.html", context)
    return render(request, "user_registration.html", {})


# Creating User logout View
def logout(request):
    del request.session["email"]
    return render(request, "user_login.html", {"success": "Logged Out Successfully :)"})


# Creating Session Validator
def is_login(request):
    if request.session.__contains__("email"):
        return True
    else:
        return False


# Creating User Homepage View
def homepage(request):
    if is_login(request):
        email = request.session["email"]
        user_data = UserRegistrationData.objects.get(email_id=email)
        context = {"login_success": "Welcome " + user_data.first_name}
        return render(request, "user_homepage.html", context)

    else:
        context = {"not_logged_in": "User not logged in :/ Please login to continue :D"}
        return render(request, "user_login.html", context)


# Creating a New Ticket View
def new_ticket(request):
    if is_login(request):
        email = request.session["email"]
        user_data = UserRegistrationData.objects.get(email_id=email)
        context = {"user": user_data}
        return render(request, "user_new_ticket.html", context)

    else:
        context = {"not_logged_in": "User not logged in :/ Please login to continue :D"}
        return render(request, "user_login.html", context)


# Saving the Ticket in the Database
def new_ticket_save(request):
    if is_login(request):
        if request.method == "POST":
            try:
                ticket_form_data = UserTicketForm(request.POST)
                print("Ticket Form Errors", ticket_form_data.errors)

                if ticket_form_data.is_valid():
                    ticket_form_data.save()

                    email = request.session["email"]
                    user_data = UserRegistrationData.objects.get(email_id=email)
                    ticket_data = UserTicket.objects.filter(user_id=user_data.id)

                    context = {"success": "Ticket Submission Successful :D", "ticket_data": ticket_data}
                    return render(request, "user_view_ticket.html", context)
                else:
                    context = {"error_message": "Uh oh! An unexpected error occurred ;-;"}
                    return render(request, "user_new_ticket.html", context)

            except Exception as error:
                print("Ticket Saving Error", error)
                context = {"error_message": "Uh oh! An unexpected error occurred ;-;"}
                return render(request, "user_new_ticket.html", context)
        return render(request, "user_new_ticket.html", {})

    else:
        context = {"not_logged_in": "User not logged in :/ Please login to continue :D"}
        return render(request, "user_login.html", context)


# Displaying Existing User Tickets
def view_tickets(request):
    if is_login(request):
        email = request.session["email"]
        user_data = UserRegistrationData.objects.get(email_id=email)
        ticket_data = UserTicket.objects.filter(user_id=user_data.id)
        context = {"ticket_data": ticket_data}
        return render(request, "user_view_ticket.html", context)
    else:
        context = {"not_logged_in": "User not logged in :/ Please login to continue :D"}
        return render(request, "user_login.html", context)


# Modifying Existing User Tickets
def edit_ticket(request, ticket_id):
    if is_login(request):
        ticket_data = UserTicket.objects.get(id=ticket_id)
        context = {"ticket_data": ticket_data}
        return render(request, "user_edit_ticket.html", context)
    else:
        context = {"not_logged_in": "User not logged in :/ Please login to continue :D"}
        return render(request, "user_login.html", context)


# Saving the Ticket Modification in the Database
def update_user_ticket(request):
    if is_login(request):
        if request.method == "POST":
            try:
                ticket_id = request.POST["id"]
                ticket_instance = UserTicket.objects.get(id=ticket_id)
                ticket_form_data = UserTicketForm(request.POST, instance=ticket_instance)
                print("Ticket Form Errors", ticket_form_data.errors)
                if ticket_form_data.is_valid():
                    ticket_form_data.save()

                    email = request.session["email"]
                    user_data = UserRegistrationData.objects.get(email_id=email)
                    ticket_data = UserTicket.objects.filter(user_id=user_data.id)

                    context = {"success": "Ticket Edited Successfully :D", "ticket_data": ticket_data}
                    return render(request, "user_view_ticket.html", context)
                else:
                    context = {"error_message": "Uh oh! An unexpected error occurred ;-;"}
                    return render(request, "user_new_ticket.html", context)

            except Exception as error:
                print("Ticket Saving Error", error)
                context = {"error_message": "Uh oh! An unexpected error occurred ;-;"}
                return render(request, "user_new_ticket.html", context)
        return render(request, "user_new_ticket.html", {})

    else:
        context = {"not_logged_in": "User not logged in :/ Please login to continue :D"}
        return render(request, "user_login.html", context)

User_Application/templates/footer.html
<footer id="footer">

    <div class="container">
     <div class="row text-center">
      <div class="me-md-auto col-md-12">
        <div class="copyright">
          &copy; Copyright <strong><span>OnePage</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/onepage-multipurpose-bootstrap-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
     </div>
    </div>
  </footer>

User_Application/templates/inner-page.html
<!DOCTYPE html>
<html lang="en">

<head>
 {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'user_header.html' %}
  <!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Inner Page</h2>
          <ol>
            <li><a href="{% url 'User_Application:homepage' %}">Home</a></li>
            <li>Inner Page</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">
        <p>
          Example inner page template
        </p>
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% include 'scripts.html' %}

</body>

</html>

User_Application/templates/scripts.html
 {% load static %}
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

User_Application/templates/user_edit_ticket.html
<!DOCTYPE html>
<html lang="en">

<head>
 {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'user_header.html' %}
  <!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>New Ticket Submission</h2>
          <ol>
            <li><a href="{% url 'User_Application:homepage' %}">Home</a></li>
            <li>New Ticket</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <center>
      <div class="container">
        <div class="col-lg-8 mt-5 mt-lg-0">
          <div class="my-3">
                <div class="sent-message text-warning">{{user_doesnt_exist}}</div>
                <div class="sent-message text-danger">{{user_exists}}</div>
          </div>

            <form action="{% url 'User_Application:UpdateUserTicket' %}" method="post" role="form">
              {% csrf_token %}

                <div class="col-md-4 form-group">
                  <input type="hidden" name="id" value="{{ticket_data.id}}" class="form-control" id="ticket_id" required readonly>
                </div>

                <div class="col-md-4 form-group">
                  <input type="hidden" name="user" value="{{ticket_data.user_id}}" class="form-control" id="user_id" required readonly>
                </div>

                <div class="col-md-8 form-group mt-3">
                  <input type="text" name="title" class="form-control" id="title" placeholder="{{ticket_data.title}}" value="{{ticket_data.title}}" required>
                </div>

              <div class="col-md-8 form-group mt-3">
                <textarea class="form-control" rows="5" name="description" id="email" placeholder="{{ticket_data.description}}" required>{{ticket_data.description}}</textarea>
                </div>

              <div><input class="btn btn-primary col-md-2 mt-3" type="submit" value="Raise a Ticket"></div>
            </form>
           <div class="my-3">
                <div class="error-message text-danger">{{error_message}}</div>
              </div>
          <div class="sent-message mt-3"><p>Raised a Ticket Earlier? &nbsp;<a class="getstarted" href="{% url 'User_Application:login' %}"><u>Check Status</u></a></p></div>
          </div>
      </div>
         </center>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% include 'scripts.html' %}

</body>

</html>

User_Application/templates/user_header.html
{% load static %}
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">

      <h1 class="logo"><a href="{% url 'User_Application:homepage' %}">Ticket Management Task</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'User_Application:homepage' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'User_Application:newTicket' %}">Raise a Ticket</a></li>
          <li><a class="nav-link scrollto" href="{% url 'User_Application:viewTickets' %}">View Tickets</a></li>
          <li class="dropdown"><a class="getstarted" href="#"><span>Profile</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Edit Profile</a></li>
              <li><a href="#">Change Password</a></li>
              <li><a href="{% url 'User_Application:logout' %}">Logout</a></li>
            </ul>
          </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header>

User_Application/templates/user_homepage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'user_header.html' %}
  <!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
      <div class="row justify-content-center">
        <div class="col-xl-7 col-lg-9 text-center">
          <h1>{{login_success}}</h1>
          <h2>Let us know your concern</h2>
        </div>
      </div>
      <div class="text-center">
        <a href="{% url 'User_Application:newTicket' %}" class="btn-get-started scrollto">Raise a Ticket</a>
      </div>

      <div class="row icon-boxes">
        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="200">
          <div class="icon-box">
            <div class="icon"><i class="ri-stack-line"></i></div>
            <h4 class="title"><a href="">Lorem Ipsum</a></h4>
            <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="300">
          <div class="icon-box">
            <div class="icon"><i class="ri-palette-line"></i></div>
            <h4 class="title"><a href="">Sed ut perspiciatis</a></h4>
            <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="400">
          <div class="icon-box">
            <div class="icon"><i class="ri-command-line"></i></div>
            <h4 class="title"><a href="">Magni Dolores</a></h4>
            <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="500">
          <div class="icon-box">
            <div class="icon"><i class="ri-fingerprint-line"></i></div>
            <h4 class="title"><a href="">Nemo Enim</a></h4>
            <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis</p>
          </div>
        </div>

      </div>
    </div>
  </section><!-- End Hero -->


  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  {% include 'scripts.html' %}

</body>

</html>

User_Application/templates/user_login.html
<!DOCTYPE html>
<html lang="en">

<head>
 {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'base_header.html' %}
  <!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>User Login</h2>
          <ol>
            <li><a href="{% url 'Base_Application:homepage' %}">Home</a></li>
            <li>User Login</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">
        <div class="col-lg-8 mt-2 mt-lg-0">
          <div class="my-3">
                <div class="sent-message text-success">{{success}}</div>
                <div class="error-message text-warning">{{not_logged_in}}</div>
          </div>

            <form action="{% url 'User_Application:login' %}" method="post" role="form">
              {% csrf_token %}
                <div class="col-md-4 form-group">
                  <input type="email" name="email_id" class="form-control" id="name" placeholder="Your Email" required>
                </div>
                <div class="col-md-4 form-group mt-3">
                  <input type="password" class="form-control" name="password" id="email" placeholder="Your password" required>
                </div>
              <div class="my-3">
                <div class="error-message text-warning">{{invalid_credentials}}</div>
                <div class="error-message text-danger">{{error_message}}</div>
              </div>
              <div><input class="btn btn-primary col-md-2 mt-3" type="submit" value="Login"></div>
            </form>
          <div class="sent-message mt-3"><p>Not a member? Get registered with us &nbsp;<a class="getstarted" href="{% url 'User_Application:registration' %}"><u>Register here</u></a></p></div>
          </div>
      </div>

    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->

  {% include 'footer.html' %}

  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% include 'scripts.html' %}

</body>

</html>

User_Application/templates/user_new_ticket.html
<!DOCTYPE html>
<html lang="en">

<head>
 {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'user_header.html' %}
  <!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>New Ticket Submission</h2>
          <ol>
            <li><a href="{% url 'User_Application:homepage' %}">Home</a></li>
            <li>New Ticket</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <center>
      <div class="container">
        <div class="col-lg-8 mt-5 mt-lg-0">
          <div class="my-3">
                <div class="sent-message text-warning">{{user_doesnt_exist}}</div>
                <div class="sent-message text-danger">{{user_exists}}</div>
          </div>

            <form action="{% url 'User_Application:newTicketSubmission' %}" method="post" role="form">
              {% csrf_token %}
                <div class="col-md-4 form-group">
                  <input type="hidden" name="user" value="{{user.id}}" class="form-control" id="user_id" required readonly>
                </div>

                <div class="col-md-8 form-group mt-3">
                  <input type="text" name="title" class="form-control" id="title" placeholder="Summarise Your Issue" required>
                </div>

              <div class="col-md-8 form-group mt-3">
                <textarea class="form-control" rows="5" name="description" id="email" placeholder="Describe your Issue" required></textarea>
                </div>

              <div><input class="btn btn-primary col-md-2 mt-3" type="submit" value="Raise a Ticket"></div>
            </form>
           <div class="my-3">
                <div class="error-message text-danger">{{error_message}}</div>
              </div>
          <div class="sent-message mt-3"><p>Raised a Ticket Earlier? &nbsp;<a class="getstarted" href="{% url 'User_Application:viewTickets' %}"><u>Check Status</u></a></p></div>
          </div>
      </div>
         </center>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% include 'scripts.html' %}

</body>

</html>

User_Application/templates/user_registration.html
<!DOCTYPE html>
<html lang="en">

<head>
 {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'base_header.html' %}
  <!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>New User Registration</h2>
          <ol>
            <li><a href="{% url 'Base_Application:homepage' %}">Home</a></li>
            <li>User Registration</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">
        <div class="col-lg-8 mt-5 mt-lg-0">
          <div class="my-3">
                <div class="sent-message text-warning">{{user_doesnt_exist}}</div>
                <div class="sent-message text-danger">{{user_exists}}</div>
          </div>

            <form action="{% url 'User_Application:registration' %}" method="post" role="form">
              {% csrf_token %}
                <div class="col-md-4 form-group">
                  <input type="text" name="first_name" class="form-control" id="first_name" placeholder="Your First Name" required>
                </div>

                <div class="col-md-4 form-group mt-3">
                  <input type="text" name="last_name" class="form-control" id="last_name" placeholder="Your Last Name" required>
                </div>

              <div class="col-md-4 form-group mt-3">
                  <input type="email" class="form-control" name="email_id" id="email" placeholder="Your Email" required>
                </div>

              <div class="col-md-4 form-group mt-3">
                <input type="number" class="form-control" name="contact_number" id="contact_number" placeholder="Your Contact Number" required>
              </div>

              <div class="col-md-4 form-group mt-3">
                <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password" required>
              </div>


              <div class="my-3">
                <div class="error-message">{{error_message}}</div>
                <div class="sent-message">{{success_message}}</div>
              </div>
              <div><input class="btn btn-primary col-md-2" type="submit" value="Register"></div>
            </form>
          <div class="sent-message mt-3"><p>Already a member? &nbsp;<a class="getstarted" href="{% url 'User_Application:login' %}"><u>Login here</u></a></p></div>
          </div>
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% include 'scripts.html' %}

</body>

</html>

User_Application/templates/user_view_ticket.html
<!DOCTYPE html>
<html lang="en">

<head>
 {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'user_header.html' %}
  <!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>View My Tickets</h2>
          <ol>
            <li><a href="{% url 'User_Application:homepage' %}">Home</a></li>
            <li>View Tickets</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">
          <div class="my-3">
                <div class="sent-message text-success">{{success}}</div>
          </div>
        <div class="row">
          {% for data in ticket_data %}
          <div class="col-sm-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{data.title}}</h5>
                <p class="card-text">{{data.description}}</p>
                <p>Status: <b class="card-text">{{data.status}}</b></p>
                <p>Created on: <b>{{data.create_on}}</b></p>
                <a href="{% url 'User_Application:editUserTicket' ticket_id=data.id %}" class="btn btn-primary">Edit Ticket</a>
              </div>
            </div><br>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% include 'scripts.html' %}

</body>

</html>