TicketManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Base_Application.urls")),
    path("user/", include("User_Application.urls")),
    path("ticket_admin/", include("Ticket_Admin.urls")),
]

Ticket_Admin/urls.py
from django.urls import path
from Ticket_Admin import views as admin_views

app_name = "Ticket_Admin"

urlpatterns = [
    path("", admin_views.login, name="login"),
    path("logout", admin_views.logout, name="logout"),
    path("home", admin_views.homepage, name="homepage"),
    path("view_user_tickets", admin_views.view_all_tickets, name="viewTickets"),
    path("edit_ticket-status/<int:ticket_id>", admin_views.edit_ticket_status, name="editTicketStatus"),
    path("update_ticket-status", admin_views.update_ticket_status, name="updateTicketStatus"),
]

User_Application/urls.py
from django.urls import path
from User_Application import views as user_views

app_name = "User_Application"

urlpatterns = [
    path("", user_views.login, name="login"),
    path("registration", user_views.registration, name="registration"),
    path("logout", user_views.logout, name="logout"),
    path("home", user_views.homepage, name="homepage"),
    path("new_ticket", user_views.new_ticket, name="newTicket"),
    path("new_ticket_submission", user_views.new_ticket_save, name="newTicketSubmission"),
    path("view_my_tickets", user_views.view_tickets, name="viewTickets"),
    path("edit_my_ticket/<int:ticket_id>", user_views.edit_ticket, name="editUserTicket"),
    path("edit_my_ticket", user_views.update_user_ticket, name="UpdateUserTicket"),
]

Ticket_Admin/models.py
from django.db import models
# from django.contrib.auth.models import User

# Create your models here.

'''class Ticket_Admin(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=50)

    def __str__(self):
        return "%s" % self.username
'''

Ticket_Admin/views.py
from django.shortcuts import render
from User_Application.models import UserTicket, UserRegistrationData
from User_Application.forms import UserTicketForm, UserRegistrationDataForm


# Create your views here.

def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        if username == "Admin" and password == "TicketAdmin@123":
            request.session["username"] = username
            context = {"login_success": "Welcome Ticket Admin"}
            return render(request, "admin_homepage.html", context)

        else:
            context = {"invalid_credentials": "You have entered Invalid Credentials :("}
            return render(request, "admin_login.html", context)
    return render(request, "admin_login.html", {})


def logout(request):
    del request.session["username"]
    return render(request, "admin_login.html", {"success": "Logged Out Successfully :)"})


def is_login(request):
    if request.session.__contains__("username"):
        return True
    else:
        return False


def homepage(request):
    if is_login(request):
        context = {"login_success": "Welcome Ticket Admin"}
        return render(request, "admin_homepage.html", context)
    else:
        context = {"not_logged_in": "Admin not logged in :/ Please login to continue :D"}
        return render(request, "admin_login.html", context)


def view_all_tickets(request):
    if is_login(request):
        ticket_data = UserTicket.objects.all()
        context = {"ticket_data": ticket_data}
        return render(request, "admin_view_all_tickets.html", context)
    else:
        context = {"not_logged_in": "Admin not logged in :/ Please login to continue :D"}
        return render(request, "admin_login.html", context)


def edit_ticket_status(request, ticket_id):
    if is_login(request):
        ticket_data = UserTicket.objects.get(id=ticket_id)
        context = {"ticket_data": ticket_data}
        return render(request, "admin_edit_ticket-status.html", context)

    else:
        context = {"not_logged_in": "Admin not logged in :/ Please login to continue :D"}
        return render(request, "admin_login.html", context)


def update_ticket_status(request):
    if is_login(request):
        ticket_id = request.POST["id"]
        status = request.POST["status"]

        ticket_status = UserTicket.objects.get(id=ticket_id)
        ticket_status.status = status
        ticket_status.save()

        ticket_data = UserTicket.objects.all()
        context = {"ticket_data": ticket_data, "success": "Ticket Status Updated Successfully :D"}
        return render(request, "admin_view_all_tickets.html", context)

    else:
        context = {"not_logged_in": "Admin not logged in :/ Please login to continue :D"}
        return render(request, "admin_login.html", context)

Ticket_Admin/templates/admin_edit_ticket-status.html
<!DOCTYPE html>
<html lang="en">

<head>
 {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'ticketAdmin_header.html' %}
  <!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Update Ticket Status</h2>
          <ol>
            <li><a href="{% url 'Ticket_Admin:homepage' %}">Home</a></li>
            <li>Update Status</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <center>
      <div class="container">
        <div class="col-lg-8 mt-5 mt-lg-0">
          <div class="my-3">
                <div class="sent-message text-warning">{{user_doesnt_exist}}</div>
                <div class="sent-message text-danger">{{user_exists}}</div>
          </div>

            <form action="{% url 'Ticket_Admin:updateTicketStatus' %}" method="post" role="form">
              {% csrf_token %}

                <div class="col-md-4 form-group">
                  <input type="hidden" name="id" value="{{ticket_data.id}}" class="form-control" id="ticket_id" required readonly>
                </div>

                <div class="col-md-4 form-group">
                  <input type="hidden" name="user" value="{{ticket_data.user_id}}" class="form-control" id="user_id" required readonly>
                </div>

                <div class="col-md-8 form-group mt-3">
                  <input type="text" name="title" class="form-control" id="title" placeholder="{{ticket_data.title}}" value="{{ticket_data.title}}" required readonly>
                </div>


              <div class="col-md-8 form-group mt-3">
                <textarea class="form-control" rows="5" name="description" id="email" placeholder="{{ticket_data.description}}" required readonly>{{ticket_data.description}}</textarea>
                </div>

              <div>
                Update Ticket Status:
                  <select name="status" class="col-md-3 form-group mt-3 text-center">
                    <option value="{{ticket_data.status}}">{{ticket_data.status}}</option>
                    <option value="Status Update 1">Status Update 1</option>
                    <option value="Status Update 2">Status Update 2</option>
                    <option value="Status Update 3">Status Update 3</option>
                  </select>
                </div>

              <div><input class="btn btn-primary col-md-2 mt-3" type="submit" value="Update Status"></div>
            </form>
           <div class="my-3">
                <div class="error-message text-danger">{{error_message}}</div>
              </div>
          </div>
      </div>
         </center>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% include 'scripts.html' %}

</body>

</html>

Ticket_Admin/templates/admin_homepage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'ticketAdmin_header.html' %}
  <!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
      <div class="row justify-content-center">
        <div class="col-xl-7 col-lg-9 text-center">
          <h1>{{login_success}}</h1>
          <h2>Respond to User Issues</h2>
        </div>
      </div>
      <div class="text-center">
        <a href="{% url 'Ticket_Admin:viewTickets' %}" class="btn-get-started scrollto">View Tickets</a>
      </div>

      <div class="row icon-boxes">
        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="200">
          <div class="icon-box">
            <div class="icon"><i class="ri-stack-line"></i></div>
            <h4 class="title"><a href="">Lorem Ipsum</a></h4>
            <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="300">
          <div class="icon-box">
            <div class="icon"><i class="ri-palette-line"></i></div>
            <h4 class="title"><a href="">Sed ut perspiciatis</a></h4>
            <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="400">
          <div class="icon-box">
            <div class="icon"><i class="ri-command-line"></i></div>
            <h4 class="title"><a href="">Magni Dolores</a></h4>
            <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="500">
          <div class="icon-box">
            <div class="icon"><i class="ri-fingerprint-line"></i></div>
            <h4 class="title"><a href="">Nemo Enim</a></h4>
            <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis</p>
          </div>
        </div>

      </div>
    </div>
  </section><!-- End Hero -->


  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  {% include 'scripts.html' %}

</body>

</html>

Ticket_Admin/templates/admin_login.html
<!DOCTYPE html>
<html lang="en">

<head>
 {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'base_header.html' %}
  <!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Ticket Admin Login</h2>
          <ol>
            <li><a href="{% url 'Ticket_Admin:homepage' %}">Home</a></li>
            <li>Admin Login</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">
        <div class="col-lg-8 mt-5 mt-lg-0">
          <div class="my-3">
                <div class="sent-message text-success">{{success}}</div>
                <div class="error-message text-warning">{{not_logged_in}}</div>
          </div>

            <form action="{% url 'Ticket_Admin:login' %}" method="post" role="form">
              {% csrf_token %}
                <div class="col-md-4 form-group">
                  <input type="text" name="username" class="form-control" id="name" placeholder="Your Email" required>
                </div>
                <div class="col-md-4 form-group mt-3">
                  <input type="password" class="form-control" name="password" id="email" placeholder="Your password" required>
                </div>
              <div class="my-3">
                <div class="error-message text-warning">{{invalid_credentials}}</div>
                <div class="error-message text-danger">{{error_message}}</div>
              </div>
              <div><input class="btn btn-primary col-md-2 mt-3" type="submit" value="Login"></div>
            </form>
          </div>
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% include 'scripts.html' %}

</body>

</html>

Ticket_Admin/templates/admin_view_all_tickets.html
<!DOCTYPE html>
<html lang="en">

<head>
 {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'ticketAdmin_header.html' %}
  <!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>View all User Tickets</h2>
          <ol>
            <li><a href="{% url 'Ticket_Admin:homepage' %}">Home</a></li>
            <li>View Tickets</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">
          <div class="my-3">
                <div class="sent-message text-success">{{success}}</div>
          </div>
        <div class="row">
          {% for data in ticket_data %}
          <div class="col-sm-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{data.title}}</h5>
                <p class="card-text">{{data.description}}</p>
                <span>User: <b class="card-text">{{data.user.first_name}}</b></span><br>
                <span>Status: <b class="card-text">{{data.status}}</b></span>
                <p>Created on: <b>{{data.create_on}}</b></p>
                <a href="{% url 'Ticket_Admin:editTicketStatus' ticket_id=data.id %}" class="btn btn-primary">Update Ticket Status</a>
              </div>
            </div><br>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% include 'scripts.html' %}

</body>

</html>

Ticket_Admin/templates/footer.html
<footer id="footer">

    <div class="container">
     <div class="row text-center">
      <div class="me-md-auto col-md-12">
        <div class="copyright">
          &copy; Copyright <strong><span>OnePage</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/onepage-multipurpose-bootstrap-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
     </div>
    </div>
  </footer>

Ticket_Admin/templates/head_links.html
{% load static %}
<meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>OnePage Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: OnePage - v4.8.1
  * Template URL: https://bootstrapmade.com/onepage-multipurpose-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->

Ticket_Admin/templates/inner-page.html
<!DOCTYPE html>
<html lang="en">

<head>
 {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'user_header.html' %}
  <!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Inner Page</h2>
          <ol>
            <li><a href="{% url 'User_Application:homepage' %}">Home</a></li>
            <li>Inner Page</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">
        <p>
          Example inner page template
        </p>
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  {% include 'scripts.html' %}

</body>

</html>

Ticket_Admin/templates/scripts.html
 {% load static %}
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

Ticket_Admin/templates/ticketAdmin_header.html
{% load static %}
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">

      <h1 class="logo"><a href="{% url 'Ticket_Admin:homepage' %}">Ticket Management Task</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'Ticket_Admin:homepage' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'Ticket_Admin:viewTickets' %}">View all Tickets</a></li>
          <li><a class="getstarted" href="{% url 'Ticket_Admin:logout' %}"><span>Logout</span></a>
          </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header>