Base_Application/urls.py
from django.urls import path
from Base_Application import views as base_views

app_name = "Base_Application"

urlpatterns = [
    path("", base_views.homepage, name="homepage"),
    path("about_us", base_views.about_us, name="about_us"),
    path("contact_us", base_views.contact_us, name="contact_us"),
]

TicketManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Base_Application.urls")),
    path("user/", include("User_Application.urls")),
    path("ticket_admin/", include("Ticket_Admin.urls")),
]

Ticket_Admin/urls.py
from django.urls import path
from Ticket_Admin import views as admin_views

app_name = "Ticket_Admin"

urlpatterns = [
    path("", admin_views.login, name="login"),
    path("logout", admin_views.logout, name="logout"),
    path("home", admin_views.homepage, name="homepage"),
    path("view_user_tickets", admin_views.view_all_tickets, name="viewTickets"),
    path("edit_ticket-status/<int:ticket_id>", admin_views.edit_ticket_status, name="editTicketStatus"),
    path("update_ticket-status", admin_views.update_ticket_status, name="updateTicketStatus"),
]

User_Application/urls.py
from django.urls import path
from User_Application import views as user_views

app_name = "User_Application"

urlpatterns = [
    path("", user_views.login, name="login"),
    path("registration", user_views.registration, name="registration"),
    path("logout", user_views.logout, name="logout"),
    path("home", user_views.homepage, name="homepage"),
    path("new_ticket", user_views.new_ticket, name="newTicket"),
    path("new_ticket_submission", user_views.new_ticket_save, name="newTicketSubmission"),
    path("view_my_tickets", user_views.view_tickets, name="viewTickets"),
    path("edit_my_ticket/<int:ticket_id>", user_views.edit_ticket, name="editUserTicket"),
    path("edit_my_ticket", user_views.update_user_ticket, name="UpdateUserTicket"),
]

Base_Application/models.py
from django.db import models


# Create your models here.

class ContactUs(models.Model):
    name = models.CharField(max_length=100)
    email_ID = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()

    objects = models.Manager()

    def __str__(self):
        return "%s" % self.subject

Base_Application/forms.py
from django import forms
from Base_Application.models import ContactUs


# Writing Forms here

class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = "__all__"

Base_Application/views.py
from django.shortcuts import render
from Base_Application.models import ContactUs
from Base_Application.forms import ContactUsForm


# Create your views here.

def homepage(request):
    return render(request, "homepage.html", {})


def about_us(request):
    return render(request, "about_us.html", {})


def contact_us(request):
    # checking the request method
    if request.method == "POST":
        contact_info = ContactUsForm(request.POST)
        print("Contact_Form_Errors: ", contact_info.errors)
        # checking the validity of the obtained form data

        if contact_info.is_valid():
            # saving the data in the database
            contact_info.save()
            success_context = {"success_message": "Your message has been sent. Thank you for contacting us!"}
            return render(request, "contact_us.html", success_context)
        else:
            contact_info = ContactUsForm(request.POST)
            # passing error message if the form data isn't valid
            error_context = {"error_message": "Oops! An unexpected error occurred", "contact_info": contact_info}
            return render(request, "contact_us.html", error_context)

    return render(request, "contact_us.html", {})

Base_Application/templates/about_us.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'base_header.html' %}
  <!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
      <div class="row justify-content-center">
        <div class="col-xl-7 col-lg-9 text-center">
          <h1>About Us</h1>
        </div>
      </div>
      </div>
    </div>
  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= About Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Who we are?</h2>
          <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. </p>
        </div>

        <div class="row content">
          <div class="col-lg-6">
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
              magna aliqua.
            </p>
            <ul>
              <li><i class="ri-check-double-line"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat</li>
              <li><i class="ri-check-double-line"></i> Duis aute irure dolor in reprehenderit in voluptate velit</li>
              <li><i class="ri-check-double-line"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat</li>
            </ul>
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0">
            <p>
              Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
              velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
              culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <a href="#" class="btn-learn-more">Learn More</a>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  {% include 'scripts.html' %}

</body>

</html>

Base_Application/templates/base_header.html
{% load static %}
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">

      <h1 class="logo"><a href="{% url 'Base_Application:homepage' %}">Ticket Management Task</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'Base_Application:homepage' %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'Base_Application:about_us' %}">About</a></li>
          <li><a class="nav-link scrollto" href="{% url 'Base_Application:contact_us' %}">Contact</a></li>
          <li class="dropdown"><a class="getstarted" href="{% url 'User_Application:login' %}"><span>Login</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="{% url 'User_Application:login' %}">Users Login</a></li>
              <li><a href="{% url 'Ticket_Admin:login' %}">Admin</a></li>
            </ul>
          </li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header>

Base_Application/templates/contact_us.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'base_header.html' %}
  <!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
      <div class="row justify-content-center">
        <div class="col-xl-7 col-lg-9 text-center">
          <h1>Contact Us</h1>
        </div>
      </div>
    </div>
  </section><!-- End Hero -->

  <main id="main">

    <!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Have a question?</h2>
          <p>Send us a message, and we'll get back to you :)</p>
        </div>

        <div class="row mt-5">

          <div class="col-lg-4">
            <div class="info">
              <div class="address">
                <i class="bi bi-geo-alt"></i>
                <h4>Location:</h4>
                <p>A108 Adam Street, New York, NY 535022</p>
              </div>

              <div class="email">
                <i class="bi bi-envelope"></i>
                <h4>Email:</h4>
                <p>info@example.com</p>
              </div>

              <div class="phone">
                <i class="bi bi-phone"></i>
                <h4>Call:</h4>
                <p>+1 5589 55488 55s</p>
              </div>

            </div>

          </div>

          <div class="col-lg-8 mt-5 mt-lg-0">

            <form action="{% url 'Base_Application:contact_us' %}" method="post" role="form">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-6 form-group">
                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                </div>
                <div class="col-md-6 form-group">
                  <input type="email" class="form-control" name="email_ID" id="email_ID" placeholder="Your Email" required>
                </div>
              </div>
              <div class="form-group mt-3">
                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
              </div>
              <div class="form-group mt-3">
                <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
              </div>
              <div class="my-3">
                <div class="error-message">{{error_message}}</div>
                <div class="sent-message">{{success_message}}</div>
              </div>
              <div class="text-center"><input class="btn btn-primary" type="submit" value="Send Message"></div>
            </form>

          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  {% include 'scripts.html' %}

</body>

</html>

Base_Application/templates/footer.html
<footer id="footer">

    <div class="container">
     <div class="row text-center">
      <div class="me-md-auto col-md-12">
        <div class="copyright">
          &copy; Copyright <strong><span>OnePage</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/onepage-multipurpose-bootstrap-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
     </div>
    </div>
  </footer>

Base_Application/templates/head_links.html
{% load static %}
<meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>OnePage Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: OnePage - v4.8.1
  * Template URL: https://bootstrapmade.com/onepage-multipurpose-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->

Base_Application/templates/homepage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  {% include 'head_links.html' %}
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'base_header.html' %}
  <!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container position-relative" data-aos="fade-up" data-aos-delay="100">
      <div class="row justify-content-center">
        <div class="col-xl-7 col-lg-9 text-center">
          <h1>Welcome to the Ticket Management System</h1>
          <h2>Register with us to have full access</h2>
        </div>
      </div>
      <div class="text-center">
        <a href="{% url 'User_Application:login' %}" class="btn-get-started scrollto">Get Started</a>
      </div>

      <div class="row icon-boxes">
        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="200">
          <div class="icon-box">
            <div class="icon"><i class="ri-stack-line"></i></div>
            <h4 class="title"><a href="">Lorem Ipsum</a></h4>
            <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="300">
          <div class="icon-box">
            <div class="icon"><i class="ri-palette-line"></i></div>
            <h4 class="title"><a href="">Sed ut perspiciatis</a></h4>
            <p class="description">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="400">
          <div class="icon-box">
            <div class="icon"><i class="ri-command-line"></i></div>
            <h4 class="title"><a href="">Magni Dolores</a></h4>
            <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia</p>
          </div>
        </div>

        <div class="col-md-6 col-lg-3 d-flex align-items-stretch mb-5 mb-lg-0" data-aos="zoom-in" data-aos-delay="500">
          <div class="icon-box">
            <div class="icon"><i class="ri-fingerprint-line"></i></div>
            <h4 class="title"><a href="">Nemo Enim</a></h4>
            <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis</p>
          </div>
        </div>

      </div>
    </div>
  </section><!-- End Hero -->


  <!-- ======= Footer ======= -->
  {% include 'footer.html' %}
  <!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  {% include 'scripts.html' %}

</body>

</html>

Base_Application/templates/scripts.html
 {% load static %}
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>